language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: AeWW2FPUTN/AA14LvK/TV6YBTr7R0mz+nReiG6XyjMdmTncboZ6m5JwqJh5peAHCYYFQIaVzJTvz111u/JARviBjRDGmeMaQkXeIe1UsehFBV4Sn2ju6KWUBX4bAak3Sfshyj5BKxiwCT83IGOUV64Ked/IwCabcbZxjfu+mnRKUpe9q0jLXS+jPP/mF08mOLVoyuDIw1lZOsBh4R1SSgh9pt1tp9X9111WbnRkfdKibp5dqwnqZYyIgovlo5drjKl9QHkua2Hz2Idqa3bXHZd5DhCzYwD0/YwhIQJUFeNeELolZIbZt2+3IE4eFhj2qJXCuFSH0i5sUFKsdFul6wWEdSrn4b+RF5T8GPJ9ONWCQLO6P5p6jlq4VRBxOLp1EGvodlusNmqgEAmxp5AFH5/pe71CQrPL8mtv1UhoiJi0MF+PGufZfHoE/IVXw0LvFCscnNCPjO1MdknsG1UHwOyF7ruPtjXFpl+cPOkF0V/AOxYyZyYWKeRuLloAxVb0vvyVrkdBiVXyANcGtuNFpDHJmPpAVWzh6NGqE3uYiM8yDlpFCMuj4mUrcHese5SrTUiNJ8bgk1IInPfz911XaUf8TBUByl0cPVR7R6flUYFY746KZC4/3YbJc35EMoCeKH6w5tRVi5nx7qj8mIzr+ZvGv0+yygs2w2BySSxmBiGg=
  app: blooming-tor-11219
  on:
    repo: xiaoma27/projet
    
addons:
  code_climate:
    repo_token: <token>
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter