language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: d04sJ9hDLVzFrJcAYkDmQjEtcX8X8Gd/iLwI7JJAK2pFewR1zuuu9e/4MiEh2aBhyLcajQgrOJJSq2gJc8mbJO8I/WOL2ZFn+9PYcs2Rv+5tnpJ/5UT/Ic6xXZxg1D+BmNXUWpMz/wiIw4oG8knPeb9ZXJsZbyvIlEp1g03q7uyhTMz9epk4tQmWWD/2kbSa3qdhck4aCJejIYMcw4+6FuGig69bNtIF4YN2MPtWAh/PBSHfSpVn2Sjvwt75H6CEtX5bsHELsy+nustCDFfoEk99BSEVngvO6pCKa2jdjlcdL0V8b+KCRuNhssSpBBphQICy0t9UY7PNPmj35GdrbIxQPilcDsUt3Tc3wJM8azINq46tCzsd3k+PnlbL3CBXMntr1WD/Kqaqn854PcNl4r46EB4NbcVxuwfzWI165Bgl+MDGI0FpTiXRXHUvLev3VYSPeSEIFupjW9ZhdKin0V8OfwEK7DKKhtob+9dhClmh6nYV+XTkcHFYU3mZQ0sUfjBXK+WGSEHzLVE8/yE7HkvaabuAlxiLYlTHornbz1u15jjQwRCKSBoj4azXHY0AAdvo69BQg5WE5+lYYmNAjcjK413cGhV+NN8ZKjc+pCB191CuGMXlZ+0i6dAlJzCZOoBgzdr/DGB48wuyIWkcRPNtF9gLkZcujfdkooZk+ws=
  app: murmuring-spire-38047
  on:
    repo: xiaoma27/projet
